# Generated by Django 4.1.7 on 2023-04-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_registration',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(choices=[('candidates', 'Candidates'), ('election_officers', 'Election Officers'), ('voters', 'Voters')], max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email_address', models.EmailField(max_length=255, unique=True)),
                ('password', models.TextField()),
                ('mobile_number', models.PositiveIntegerField()),
                ('aadhaar_number', models.TextField()),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='users/')),
                ('address_line_1', models.CharField(max_length=500)),
                ('address_line_2', models.CharField(blank=True, max_length=500, null=True)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=10)),
                ('pin_code', models.CharField(max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active')], default='pending', max_length=15)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
