# Generated by Django 4.1.7 on 2023-04-12 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='messages_index',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('recipient_user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_images_conn', to='elections.user_registration')),
                ('sender_user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sender_images_conn', to='elections.user_registration')),
            ],
        ),
        migrations.CreateModel(
            name='messages_contain',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('messages_text', models.TextField(default='')),
                ('message_type', models.CharField(choices=[('normal', 'Normal'), ('project', 'Project')], default='normal', max_length=15)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('msg_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_index_conn', to='elections.messages_index')),
                ('participant_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elections.user_registration')),
            ],
        ),
    ]
