# Generated by Django 4.1.7 on 2023-04-13 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_messages_index_messages_contain'),
    ]

    operations = [
        migrations.CreateModel(
            name='elections',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('election_date', models.DateField()),
                ('election_start_time', models.TimeField()),
                ('election_end_time', models.TimeField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='election_votes',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('votes', models.CharField(max_length=10)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('candidates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates_conn', to='elections.user_registration')),
                ('elections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elections_conn', to='elections.elections')),
                ('voters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voters_conn', to='elections.user_registration')),
            ],
        ),
        migrations.CreateModel(
            name='election_candidates',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('candidates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.user_registration')),
                ('elections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.elections')),
            ],
        ),
    ]
