# Generated by Django 4.1.7 on 2023-04-13 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_elections_election_votes_election_candidates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='election_votes',
            old_name='votes',
            new_name='vote',
        ),
    ]
