# Generated by Django 4.1.7 on 2023-04-13 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_rename_votes_election_votes_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='elections',
            name='election_officers',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='election_officers_conn', to='elections.user_registration'),
            preserve_default=False,
        ),
    ]
