# Generated by Django 4.1.7 on 2023-04-16 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0006_rename_election_date_elections_election_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elections',
            name='election_end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='elections',
            name='election_end_time',
            field=models.TimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='elections',
            name='election_start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='elections',
            name='election_start_time',
            field=models.TimeField(default=datetime.date.today),
        ),
    ]
