# Generated by Django 4.1.7 on 2023-04-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0007_alter_elections_election_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elections',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='election_officers/'),
        ),
        migrations.AddField(
            model_name='elections',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active')], default='active', max_length=15),
        ),
    ]
