# Generated by Django 4.1.7 on 2023-04-16 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0008_elections_logo_image_elections_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elections',
            name='election_end_date',
        ),
        migrations.RemoveField(
            model_name='elections',
            name='election_end_time',
        ),
        migrations.RemoveField(
            model_name='elections',
            name='election_start_date',
        ),
        migrations.RemoveField(
            model_name='elections',
            name='election_start_time',
        ),
        migrations.AddField(
            model_name='elections',
            name='election_end_date_time',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='elections',
            name='election_start_date_time',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
