# Generated by Django 4.1.7 on 2023-04-16 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0009_remove_elections_election_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elections',
            name='election_end_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='elections',
            name='election_start_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
