# Generated by Django 4.2 on 2023-04-23 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0012_user_registration_otp_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages_contain',
            name='message_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('election', 'Election')], default='normal', max_length=15),
        ),
        migrations.AlterField(
            model_name='messages_index',
            name='recipient_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_msg_conn', to='elections.user_registration'),
        ),
        migrations.AlterField(
            model_name='messages_index',
            name='sender_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sender_msg_conn', to='elections.user_registration'),
        ),
    ]
