# Generated by Django 4.2 on 2023-04-24 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0014_alter_elections_status_election_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election_parties',
            name='elections',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='election_parties_conn', to='elections.elections'),
        ),
        migrations.AlterField(
            model_name='election_parties',
            name='party_image',
            field=models.ImageField(blank=True, null=True, upload_to='election_party/'),
        ),
        migrations.AlterField(
            model_name='election_position',
            name='elections',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='election_position_conn', to='elections.elections'),
        ),
    ]
