# Generated by Django 4.2 on 2023-04-25 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0015_alter_election_parties_elections_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elections',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('ready', 'Ready'), ('pending', 'Pending'), ('active', 'Active')], default='pending', max_length=15),
        ),
    ]
