# Generated by Django 4.1.7 on 2023-04-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0018_election_candidates_party_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='election_candidates',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('applied', 'applied'), ('active', 'Active'), ('rejected', 'Rejected')], default='pending', max_length=15),
        ),
    ]
