# Generated by Django 4.1.7 on 2023-04-26 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0019_election_candidates_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election_candidates',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='election_candidates_position_conn', to='elections.election_position'),
        ),
    ]
