# Generated by Django 4.1.7 on 2023-04-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0020_alter_election_candidates_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='election_candidates',
            name='symbol_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
