# Generated by Django 4.1.7 on 2023-04-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0021_election_candidates_symbol_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='election_candidates',
            name='note_c',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='election_candidates',
            name='note_eo',
            field=models.TextField(default=''),
        ),
    ]
