# Generated by Django 4.1.7 on 2023-04-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0022_election_candidates_note_c_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election_candidates',
            name='note_c',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='election_candidates',
            name='note_eo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
