# Generated by Django 4.1.7 on 2023-04-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0023_alter_election_candidates_note_c_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election_candidates',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('accepted', 'Accepted'), ('active', 'Active'), ('rejected', 'Rejected')], default='pending', max_length=15),
        ),
    ]
