# Generated by Django 4.1.7 on 2023-04-29 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0024_alter_election_candidates_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='election_votes',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='position_conn', to='elections.election_position'),
            preserve_default=False,
        ),
    ]
