# Generated by Django 4.1.7 on 2023-05-02 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0026_alter_election_votes_candidates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages_contain',
            options={'verbose_name': 'Messages Contain', 'verbose_name_plural': 'Messages Contains'},
        ),
        migrations.AlterModelOptions(
            name='messages_index',
            options={'verbose_name': 'Messages Index', 'verbose_name_plural': 'Messages Indexs'},
        ),
        migrations.AlterModelOptions(
            name='user_registration',
            options={'verbose_name': 'User Registration', 'verbose_name_plural': 'User Registrations'},
        ),
        migrations.AlterField(
            model_name='messages_contain',
            name='message_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('campaign', 'Campaign')], default='normal', max_length=15),
        ),
        migrations.AlterField(
            model_name='messages_index',
            name='recipient_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_images_conn', to='elections.user_registration'),
        ),
        migrations.AlterField(
            model_name='messages_index',
            name='sender_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sender_images_conn', to='elections.user_registration'),
        ),
    ]
