# Generated by Django 4.1.7 on 2023-05-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0027_alter_messages_contain_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election_candidates',
            name='symbol',
            field=models.FileField(blank=True, null=True, upload_to='candidates/'),
        ),
    ]
