# Generated by Django 4.1.7 on 2023-05-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0028_alter_election_candidates_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election_candidates',
            name='manifestos',
            field=models.FileField(blank=True, null=True, upload_to='candidates/'),
        ),
        migrations.AlterField(
            model_name='election_candidates',
            name='symbol',
            field=models.ImageField(blank=True, null=True, upload_to='candidates/'),
        ),
    ]
