# Generated by Django 4.1.7 on 2023-05-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0029_alter_election_candidates_manifestos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages_contain',
            name='message_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('campaign', 'Campaign'), ('candidates', 'Candidates')], default='normal', max_length=15),
        ),
    ]
