# Generated by Django 4.1.7 on 2023-05-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0030_alter_messages_contain_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages_contain',
            name='message_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('campaign', 'Campaign'), ('candidates_accepted', 'Candidates Accepted'), ('candidates_rejected', 'Candidates Rejected')], default='normal', max_length=25),
        ),
    ]
